version: '3.5'

services:
  postgres:
    container_name: postgres
    restart: always
    ports:
      - "5436:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=users
    image: postgres:15.0-alpine3.16
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql