version: '3.5'

services:
  postgres:
    container_name: postgres
    restart: always
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=users #postgres
      - POSTGRES_SSLMODE=disable
    image: postgres:15.0-alpine3.16
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  wallet-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: ./wallet-app
    ports:
      - "8888:8888"
      - "50051:50051"
    depends_on:
      - postgres
    environment:
     - CONFIG_PATH=/go/config.yaml
     - POSTGRES_HOST=host.docker.internal
     - POSTGRES_PORT=5436
