// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.0
// source: server.proto

package spec

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Server_CreateUser_FullMethodName                 = "/grpcAvito.Server/CreateUser"
	Server_UserBalanceAccrual_FullMethodName         = "/grpcAvito.Server/UserBalanceAccrual"
	Server_UserOrderReservation_FullMethodName       = "/grpcAvito.Server/UserOrderReservation"
	Server_UserOrderRevenue_FullMethodName           = "/grpcAvito.Server/UserOrderRevenue"
	Server_UserOrderDeleteReservation_FullMethodName = "/grpcAvito.Server/UserOrderDeleteReservation"
	Server_CreateMonthReport_FullMethodName          = "/grpcAvito.Server/CreateMonthReport"
	Server_GetBalance_FullMethodName                 = "/grpcAvito.Server/GetBalance"
)

// ServerClient is the client API for Server service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServerClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserReply, error)
	UserBalanceAccrual(ctx context.Context, in *UserBalanceAccrualRequest, opts ...grpc.CallOption) (*UserBalanceAccrualReply, error)
	UserOrderReservation(ctx context.Context, in *UserOrderReservationRequest, opts ...grpc.CallOption) (*UserOrderReservationReply, error)
	UserOrderRevenue(ctx context.Context, in *UserOrderRevenueRequest, opts ...grpc.CallOption) (*UserOrderRevenueReply, error)
	UserOrderDeleteReservation(ctx context.Context, in *UserOrderDeleteReservationRequest, opts ...grpc.CallOption) (*UserOrderDeleteReservationReply, error)
	CreateMonthReport(ctx context.Context, in *CreateMonthReportRequest, opts ...grpc.CallOption) (*CreateMonthReportReply, error)
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceReply, error)
}

type serverClient struct {
	cc grpc.ClientConnInterface
}

func NewServerClient(cc grpc.ClientConnInterface) ServerClient {
	return &serverClient{cc}
}

func (c *serverClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserReply, error) {
	out := new(CreateUserReply)
	err := c.cc.Invoke(ctx, Server_CreateUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) UserBalanceAccrual(ctx context.Context, in *UserBalanceAccrualRequest, opts ...grpc.CallOption) (*UserBalanceAccrualReply, error) {
	out := new(UserBalanceAccrualReply)
	err := c.cc.Invoke(ctx, Server_UserBalanceAccrual_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) UserOrderReservation(ctx context.Context, in *UserOrderReservationRequest, opts ...grpc.CallOption) (*UserOrderReservationReply, error) {
	out := new(UserOrderReservationReply)
	err := c.cc.Invoke(ctx, Server_UserOrderReservation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) UserOrderRevenue(ctx context.Context, in *UserOrderRevenueRequest, opts ...grpc.CallOption) (*UserOrderRevenueReply, error) {
	out := new(UserOrderRevenueReply)
	err := c.cc.Invoke(ctx, Server_UserOrderRevenue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) UserOrderDeleteReservation(ctx context.Context, in *UserOrderDeleteReservationRequest, opts ...grpc.CallOption) (*UserOrderDeleteReservationReply, error) {
	out := new(UserOrderDeleteReservationReply)
	err := c.cc.Invoke(ctx, Server_UserOrderDeleteReservation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) CreateMonthReport(ctx context.Context, in *CreateMonthReportRequest, opts ...grpc.CallOption) (*CreateMonthReportReply, error) {
	out := new(CreateMonthReportReply)
	err := c.cc.Invoke(ctx, Server_CreateMonthReport_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceReply, error) {
	out := new(GetBalanceReply)
	err := c.cc.Invoke(ctx, Server_GetBalance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerServer is the server API for Server service.
// All implementations must embed UnimplementedServerServer
// for forward compatibility
type ServerServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserReply, error)
	UserBalanceAccrual(context.Context, *UserBalanceAccrualRequest) (*UserBalanceAccrualReply, error)
	UserOrderReservation(context.Context, *UserOrderReservationRequest) (*UserOrderReservationReply, error)
	UserOrderRevenue(context.Context, *UserOrderRevenueRequest) (*UserOrderRevenueReply, error)
	UserOrderDeleteReservation(context.Context, *UserOrderDeleteReservationRequest) (*UserOrderDeleteReservationReply, error)
	CreateMonthReport(context.Context, *CreateMonthReportRequest) (*CreateMonthReportReply, error)
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceReply, error)
	mustEmbedUnimplementedServerServer()
}

// UnimplementedServerServer must be embedded to have forward compatible implementations.
type UnimplementedServerServer struct {
}

func (UnimplementedServerServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedServerServer) UserBalanceAccrual(context.Context, *UserBalanceAccrualRequest) (*UserBalanceAccrualReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserBalanceAccrual not implemented")
}
func (UnimplementedServerServer) UserOrderReservation(context.Context, *UserOrderReservationRequest) (*UserOrderReservationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserOrderReservation not implemented")
}
func (UnimplementedServerServer) UserOrderRevenue(context.Context, *UserOrderRevenueRequest) (*UserOrderRevenueReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserOrderRevenue not implemented")
}
func (UnimplementedServerServer) UserOrderDeleteReservation(context.Context, *UserOrderDeleteReservationRequest) (*UserOrderDeleteReservationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserOrderDeleteReservation not implemented")
}
func (UnimplementedServerServer) CreateMonthReport(context.Context, *CreateMonthReportRequest) (*CreateMonthReportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMonthReport not implemented")
}
func (UnimplementedServerServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedServerServer) mustEmbedUnimplementedServerServer() {}

// UnsafeServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerServer will
// result in compilation errors.
type UnsafeServerServer interface {
	mustEmbedUnimplementedServerServer()
}

func RegisterServerServer(s grpc.ServiceRegistrar, srv ServerServer) {
	s.RegisterService(&Server_ServiceDesc, srv)
}

func _Server_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_UserBalanceAccrual_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserBalanceAccrualRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).UserBalanceAccrual(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_UserBalanceAccrual_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).UserBalanceAccrual(ctx, req.(*UserBalanceAccrualRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_UserOrderReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserOrderReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).UserOrderReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_UserOrderReservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).UserOrderReservation(ctx, req.(*UserOrderReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_UserOrderRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserOrderRevenueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).UserOrderRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_UserOrderRevenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).UserOrderRevenue(ctx, req.(*UserOrderRevenueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_UserOrderDeleteReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserOrderDeleteReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).UserOrderDeleteReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_UserOrderDeleteReservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).UserOrderDeleteReservation(ctx, req.(*UserOrderDeleteReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_CreateMonthReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMonthReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).CreateMonthReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_CreateMonthReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).CreateMonthReport(ctx, req.(*CreateMonthReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Server_ServiceDesc is the grpc.ServiceDesc for Server service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Server_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcAvito.Server",
	HandlerType: (*ServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _Server_CreateUser_Handler,
		},
		{
			MethodName: "UserBalanceAccrual",
			Handler:    _Server_UserBalanceAccrual_Handler,
		},
		{
			MethodName: "UserOrderReservation",
			Handler:    _Server_UserOrderReservation_Handler,
		},
		{
			MethodName: "UserOrderRevenue",
			Handler:    _Server_UserOrderRevenue_Handler,
		},
		{
			MethodName: "UserOrderDeleteReservation",
			Handler:    _Server_UserOrderDeleteReservation_Handler,
		},
		{
			MethodName: "CreateMonthReport",
			Handler:    _Server_CreateMonthReport_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _Server_GetBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
