---
server:
  port: 8888
  host_port: localhost:8888
  domain: https://decide-career.com
  log_path: logrus.log

postgres:
  host: localhost
  port: 5436
  user: admin
  pass: admin
  name: postgres
  db_migrations: server/db/migrations
  ssl_mode: disable

grpc:
  port: 50051
  host_port: localhost:50051

...