---
server:
  port: 8888
  host_port: 0.0.0.0:8888
  log_path: logrus.log
  duration: 10000000000 #10 seconds

postgres:
  host: host.docker.internal #localhost
  port: 5436
  user: admin
  pass: admin
  name: users #postgres
  ssl_mode: disable

grpc:
  port: 50051
  host_port: 0.0.0.0:50051

...